const express = require('express');
const router = express.Router();
const Policy = require('../models/Policy');
const { protect } = require('../middleware/auth');

// Get policies
router.get('/', async (req, res) => {
  try {
    let policy = await Policy.findOne();
    if (!policy) {
      // Create default policy if none exists
      const defaultPolicy = new Policy({
        shippingPolicy: `<h3>Shipping Policy</h3>
<ul>
  <li>All transportation outside Erode will be sent in Thermocol Box - ₹500</li>
  <li>Minimum order value of ₹3000 for shipping outside Tamil Nadu</li>
  <li>Transportation charges depend upon the state and districts (Flights and Buses)</li>
  <li>Unboxing video (clear video of fish inside the packet) must be sent within 4 hours of arrival for dead on arrival claims</li>
  <li>Dead on arrival will be compensated with fishes on next shipment (sizes can vary)</li>
  <li>Live fishes once sold cannot be returned</li>
</ul>`,
        refundPolicy: `<h3>Refund Policy</h3>
<p>At Erode Marine Aquarium, we take great care to ensure that every product and livestock item reaches you in healthy and excellent condition.</p>
<h4>🐠 Live Arrival Guarantee (DOA Policy)</h4>
<p>We provide a DOA (Dead on Arrival) Guarantee for all livestock orders.</p>
<p>In the rare event that your livestock arrives in unsatisfactory condition, you must report the issue within 2 hours of delivery with clear, unopened package photos or videos as proof.</p>
<p>Verified DOA cases will be compensated with store credit or replacement in your next order.</p>
<h4>📦 Non-Returnable Items</h4>
<p>Livestock, aquarium plants, and other perishable products cannot be returned or exchanged once delivered.</p>
<p>Shipping and handling charges are not covered under the DOA policy.</p>
<h4>📝 Important Notes</h4>
<p>Our policies are designed to protect both our customers and our commitment to quality. Please review carefully before purchase.</p>`,
        termsAndConditions: `<h3>Terms of Service</h3>

<p>This document is an electronic record in terms of the Information Technology Act, 2000 and the rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, which require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name of this website, including its related mobile site and applications (hereinafter referred to as the "Platform").</p>

<h4>Platform Owner</h4>

<p>The Platform is owned by Erode Marine Aquarium, a business operating under applicable Indian laws, having its place of business at:</p>

<p><strong>Erode Marine Aquarium</strong><br>
1/65, Thilagar Street<br>
Veerappan Chatram<br>
Erode – 638004<br>
Tamil Nadu, India</p>

<p>(Hereinafter referred to as "Platform Owner", "we", "us", or "our")</p>

<h4>Acceptance of Terms</h4>

<p>Your use of the Platform and its services ("Services") is governed by these Terms of Service ("Terms"). By accessing, browsing, or using the Platform in any manner, you agree to be bound by these Terms along with all applicable policies.</p>

<p>If you do not agree with any part of these Terms, please do not use the Platform.</p>

<p>The Platform Owner reserves the right to modify these Terms at any time without prior notice. It is your responsibility to review these Terms periodically to stay informed of updates.</p>

<h4>User Definition</h4>

<p>For the purpose of these Terms, "you", "your", or "user" shall mean any natural or legal person who accesses, browses, or uses the Platform or avails the Services.</p>

<h4>Use of the Platform</h4>

<ul>
  <li>You agree to provide true, accurate, and complete information wherever required.</li>
  <li>You shall be responsible for all activities conducted through your use of the Platform.</li>
  <li>You agree not to use the Platform for any unlawful, illegal, or prohibited purpose under Indian law.</li>
</ul>

<h4>Products and Services</h4>

<ul>
  <li>The Platform offers aquarium-related products and services, including live fish, accessories, and related items.</li>
  <li>Availability of products may change without notice.</li>
  <li>Prices are subject to change at the sole discretion of the Platform Owner.</li>
</ul>

<h4>Live Fish Disclaimer</h4>

<ul>
  <li>Live fish health depends on tank conditions, water quality, feeding, and maintenance.</li>
  <li>We are not responsible for fish mortality due to improper tank conditions, mishandling, or negligence after purchase.</li>
  <li>Once sold, live fish are not eligible for return or refund, unless explicitly stated otherwise.</li>
</ul>

<h4>Images Disclaimer</h4>

<ul>
  <li>Product images displayed on the Platform are for reference purposes only.</li>
  <li>Actual fish size, color, and appearance may vary due to natural and environmental factors.</li>
</ul>

<h4>Payments</h4>

<ul>
  <li>Payments may be accepted through Instagram, WhatsApp, PhonePe, or other approved payment methods.</li>
  <li>By making a payment, you agree to the pricing, payment terms, and conditions applicable at the time of purchase.</li>
</ul>

<h4>Third-Party Links</h4>

<p>The Platform may contain links to third-party websites or services. Upon accessing these links, you will be governed by the respective third party's terms and policies. The Platform Owner is not responsible for the content or practices of such third-party websites.</p>

<h4>Intellectual Property Rights</h4>

<p>All content on the Platform, including but not limited to text, images, design, layout, graphics, and logos, is the property of the Platform Owner and is protected under applicable intellectual property laws. Unauthorized use of the Platform's content is strictly prohibited.</p>

<h4>Limitation of Liability</h4>

<ul>
  <li>The Platform and Services are provided on an "as-is" and "as-available" basis.</li>
  <li>The Platform Owner shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Platform or Services.</li>
  <li>Your use of the Platform is solely at your own risk.</li>
</ul>

<h4>Indemnification</h4>

<p>You agree to indemnify and hold harmless the Platform Owner, its representatives, and affiliates from any claims, losses, damages, or expenses arising out of your violation of these Terms, applicable laws, or the rights of any third party.</p>

<h4>Force Majeure</h4>

<p>The Platform Owner shall not be liable for failure or delay in performance due to events beyond reasonable control, including but not limited to natural disasters, government actions, or technical failures.</p>

<h4>Governing Law & Jurisdiction</h4>

<ul>
  <li>These Terms shall be governed by and construed in accordance with the laws of India.</li>
  <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of Erode, Tamil Nadu.</li>
</ul>

<h4>Contact Information</h4>

<p>For any questions, concerns, or communications regarding these Terms, please contact us using the details provided on the Platform via Instagram, WhatsApp, or PhonePe.</p>`,
        privacyPolicy: `<h3>Privacy Policy</h3>
<p>At Erode Marine Aquarium, we are committed to protecting your privacy and ensuring the security of your personal information.</p>
<h4>Information We Collect</h4>
<ul>
  <li>Name, email, phone number for order processing</li>
  <li>Shipping and billing addresses</li>
  <li>Payment information (processed securely through third-party providers)</li>
  <li>Order history and preferences</li>
</ul>
<h4>How We Use Your Information</h4>
<p>We use your information to process orders, provide customer service, and improve our services. We do not sell or share your personal information with third parties except as necessary for order fulfillment.</p>
<h4>Data Security</h4>
<p>We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.</p>`
      });
      await defaultPolicy.save();
      return res.json(defaultPolicy);
    }
    res.json(policy);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Update policies (admin only)
router.put('/', protect, async (req, res) => {
  try {
    const { shippingPolicy, refundPolicy, termsAndConditions, privacyPolicy } = req.body;
    let policy = await Policy.findOne();
    if (!policy) {
      policy = new Policy({ shippingPolicy, refundPolicy, termsAndConditions, privacyPolicy });
    } else {
      policy.shippingPolicy = shippingPolicy;
      policy.refundPolicy = refundPolicy;
      policy.termsAndConditions = termsAndConditions;
      policy.privacyPolicy = privacyPolicy;
    }
    await policy.save();
    res.json(policy);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;